[package]
name = "relo"
version = "0.1.5"
edition = "2021"
license = "Apache-2.0"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yml = "0.0.13"
anyhow = "1"
thiserror = "2"
indexmap = { version = "2", features = ["serde"] }
shellexpand = "3"
