[package]
name = "relo"
version = "0.1.8"
edition = "2021"
license = "Apache-2.0"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yml = "0.0.13"
anyhow = "1"
thiserror = "2"
indexmap = { version = "2", features = ["serde"] }
shellexpand = "3"
sha2 = "0.10"
serde_json = "1"
windows-sys = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Registry",
  "Win32_System_Environment",
  "Win32_System_Threading",
  "Win32_UI_WindowsAndMessaging",
] }

[target.'cfg(windows)'.dependencies]
junction = "2"

[features]
check-windows = []
